"""fix wrong column service_version_and_roundtrip_identfiers

Revision ID: 21cd0e8f00f7
Revises: f94db5345d98
Create Date: 2025-10-26 21:34:31.103843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21cd0e8f00f7"
down_revision: Union[str, None] = "f94db5345d98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sailings",
        sa.Column(
            "service_version_and_roundtrip_identfiers", sa.String(length=255), nullable=False
        ),
    )
    op.drop_column("sailings", "service_version_and_roundtrip_identifiers")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sailings",
        sa.Column(
            "service_version_and_roundtrip_identifiers",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("sailings", "service_version_and_roundtrip_identfiers")
    # ### end Alembic commands ###
