"""add index

Revision ID: 58462baa962f
Revises: b6d2f47fc83c
Create Date: 2025-10-27 15:35:40.496459

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58462baa962f"
down_revision: Union[str, None] = "b6d2f47fc83c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_sailings_general_query_pattern",
        "sailings",
        ["origin", "destination", "origin_at_utc"],
        unique=False,
    )
    op.create_unique_constraint(None, "sailings", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sailings", type_="unique")
    op.drop_index("idx_sailings_general_query_pattern", table_name="sailings")
    # ### end Alembic commands ###
