"""create data table

Revision ID: f94db5345d98
Revises:
Create Date: 2025-10-26 11:23:39.151703

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f94db5345d98"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sailings",
        sa.Column("origin", sa.String(length=255), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=False),
        sa.Column("origin_port_code", sa.String(length=255), nullable=False),
        sa.Column("destination_port_code", sa.String(length=255), nullable=False),
        sa.Column(
            "service_version_and_roundtrip_identifiers", sa.String(length=255), nullable=False
        ),
        sa.Column("origin_service_version_and_master", sa.String(length=255), nullable=False),
        sa.Column("destination_service_version_and_master", sa.String(length=255), nullable=False),
        sa.Column("origin_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("offered_capacity_teu", sa.Integer, nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sailings")
    # ### end Alembic commands ###
