name: Shipping Capacity

services:
  app-fastapi:
    image: app-fastapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - .:/app
    ports:
      - "80:8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_interval: 10s
      start_period: 30s
    depends_on:
      - postgres
    env_file: .env
    networks:
      - main

  # ---------------------------------- Databases ----------------------------------
  postgres:
    image: postgres:17.2
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - database.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d local" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    networks:
      - main
  # ---------------------------------- Databases ----------------------------------

networks:
  main:

volumes:
  postgres:
